Feature: Add slam_toolbox option for navigation2
Interbotix/interbotix_ros_rovers pull request #33
Opened 2023-02-11 18:35 UTC by stephenadhi

Hi,

I hope the commits and coding style fit your conventions. So in this PR, I have finished your _slam_toolbox_devel_ branch. Everything is now integrated into the humble version and running smoothly using simulation.  

**Summary**

[xslocobot_descriptions]
1. lidar.urdf.xacro
- Appended missing namespace to the LaserScan topic.

[xslocobot_nav]
1. xslocobot_slam_toolbox.launch.py
- Added sync slam toolbox node in slam_toolbox.launch.py (previously only async and localization).
- Added launch argument of slam_toolbox_mode: 'true' when including the nav2_bringup launch file.
- Added launch argument of map yaml file in the case of localization mode (default='')
2. xslocobot_nav2_bringup.launch.py 
- Galactic to Humble migration: rename the nav2_recoveries to nav2_behaviors.
- Added _tf_remappings_ to specific nodes following https://github.com/ros-planning/navigation2/tree/humble/nav2_bringup/launch.
- Added conditioning of use slam toolbox (default: false)
- Automatic launching of nav2_nodes such as _amcl_, _lifecycle manager slam_, _lifecycle manager localization_, _map server,_ and _map saver server_, conditioned on the passed slam_mode launch argument.

3. nav2_params.yaml
- Galactic to Humble migration: rename the nav2_recoveries to nav2_behaviors.
- Fix costmap issues (sensor out of bounds error), change default values.
- Global costmap default: height x width 20 x 20m, resolution: 0.1.
- Place robot at the centre of the global costmap (origin -10.0, -10.0).
- Local costmap default: height x width 5 x 5m, resolution: 0.05.

[xslocobot_sim]
1. xslocobot_gz_classic.rviz
- Additional RViZ config for visualizing map and costmap topics.
- Change scan topic to /locobot/scan.

**Testing**
1. Launch simulator with RViZ
`ros2 launch interbotix_xslocobot_sim xslocobot_gz_classic.launch.py robot_model:=locobot_base robot_name:=locobot use_lidar:=true use_rviz:=true use_gazebo_gui:=true
`
2. Launch slam_toolbox
`ros2 launch interbotix_xslocobot_nav xslocobot_slam_toolbox.launch.py launch_driver:=false use_sim_time:=false slam_mode:=online_sync`

![image](https://user-images.githubusercontent.com/32376039/218275016-e919bf7d-17ff-4cbc-bbcf-d4e4abaf8190.png)

2023-02-16 21:40 UTC, LSinterbotix commented on interbotix_ros_xslocobots/interbotix_xslocobot_nav/launch/xslocobot_nav2_bringup.launch.py
> +from multiprocessing import Condition
```suggestion
```

2023-02-16 21:41 UTC, LSinterbotix commented on interbotix_ros_xslocobots/interbotix_xslocobot_nav/launch/xslocobot_nav2_bringup.launch.py
> +
```suggestion
```

2023-02-16 21:42 UTC, LSinterbotix commented on interbotix_ros_xslocobots/interbotix_xslocobot_nav/launch/xslocobot_nav2_bringup.launch.py
> +    slam_toolbox_mode_launch_arg = LaunchConfiguration('slam_toolbox_mode')
```suggestion
```

2023-02-16 21:45 UTC, LSinterbotix commented on interbotix_ros_xslocobots/interbotix_xslocobot_nav/launch/xslocobot_nav2_bringup.launch.py
> +            description='log'
```suggestion
            description='set the logging level of the Nav2 nodes.'
```

2023-02-16 21:46 UTC, LSinterbotix requested changes
Tested this locally and everything works great! Just a few minor nits and style changes before we merge.

2023-02-17 00:22 UTC, stephenadhi commented
Hi Luke, 

I applied the changes, and should be ready to merge! 

A note regarding localization mode: I found that slam_toolbox needs to take in a pose-graph map instead of a yaml file. So I suggest only using amcl when bringing up the nav2 nodes and remove localization option offered by slam_toolbox. 

I also found more issues with nav2, for example, the new syntaxes in nav2_behavior_server and failing to plan when given a goal. 

I should be able to fix those issues by next week or so, and make new PRs. Please let me know whether you would like to actively work on these issues, so we don't work on the same thing!

Thanks,
 
Stephen

2023-02-17 23:13 UTC, LSinterbotix approved these changes

2023-02-17 23:13 UTC, merged

2023-02-17 23:17 UTC, LSinterbotix commented
@stephenadhi 

> Please let me know whether you would like to actively work on these issues, so we don't work on the same thing!

Yes, please do! Thanks again for your great contributions!